Fix wso2/product-apim#7914
wso2/carbon-identity-framework pull request #2939
Opened 2020-05-18 05:11 UTC by msm1992

### Proposed changes in this pull request
This PR adds the fix for https://github.com/wso2/product-apim/issues/7914.

2020-11-11 16:46 UTC, IsuraD commented on components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/dao/ClaimDialectDAO.java
> +        return e instanceof SQLIntegrityConstraintViolationException
This should be supported for all the supported db types and versions.

2020-11-11 16:55 UTC, IsuraD commented on components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/exception/DuplicateClaimException.java
> +}
need to add a new line

2020-11-11 17:18 UTC, IsuraD requested changes
Please check the comments

2021-02-02 07:32 UTC, DMHP commented
@msm1992 
Thanks for the contribution. I will close the PR until the comments resolved. Please re-open once it is resolved.

2021-02-02 07:32 UTC, closed without merging