Use client authentication for authentication context internal API calls instead of Mutual SSL
wso2/carbon-identity-framework pull request #3968
Opened 2022-03-24 15:42 UTC by deshankoswatte

### Proposed changes in this pull request
- This pull request makes sure that client authentication for authentication context internal API calls instead of Mutual SSL.
- Fixes: https://github.com/wso2/product-is/issues/11251.

### Checklist (for reviewing)

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description.
- [ ] **Is the PR labeled correctly?**

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled.

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests.
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/).

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components.
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?**
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes should be documented.
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented.
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

2022-08-03 05:39 UTC, rksk requested changes

2022-08-03 05:39 UTC, rksk commented on features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/EndpointConfig.properties.j2
> +basic.auth.password={{identity.auth_framework.endpoint.basic_auth_password}}
```suggestion
identity.server.service.access.username={{identity.auth_framework.endpoint.username}}
identity.server.service.access.password={{identity.auth_framework.endpoint.password}}
```

2022-08-03 05:39 UTC, rksk commented on features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/RecoveryEndpointConfig.properties.j2
> +basic.auth.password={{identity.auth_framework.endpoint.basic_auth_password}}
```suggestion
```

2022-08-03 05:39 UTC, rksk commented on features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/RecoveryEndpointConfig.properties
> +basic.auth.password=admin
```suggestion
```

2022-08-03 05:39 UTC, rksk commented on features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/EndpointConfig.properties
> +basic.auth.password=admin
```suggestion
identity.server.service.access.username=admin
identity.server.service.access.password=admin
```

2022-08-03 05:39 UTC, rksk commented on components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/Constants.java
> +    public static final String CONFIG_BASIC_AUTH_PASSWORD = "basic.auth.password";
```suggestion
    public static final String CONFIG_BASIC_AUTH_NAME = "identity.server.service.access.username";
    public static final String CONFIG_BASIC_AUTH_PASSWORD = "identity.server.service.access.password";
```

2022-08-03 05:39 UTC, rksk commented on components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointConstants.java
> +        public static final String BASIC_AUTH_PASSWORD = "basic.auth.password";
```suggestion
        public static final String BASIC_AUTH_NAME = "identity.server.service.access.username";
        public static final String BASIC_AUTH_PASSWORD = "identity.server.service.access.password";
```

2022-08-04 05:52 UTC, deshankoswatte commented on components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointConstants.java
> +        public static final String BASIC_AUTH_PASSWORD = "basic.auth.password";
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-04 05:52 UTC, deshankoswatte commented on components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/Constants.java
> +    public static final String CONFIG_BASIC_AUTH_PASSWORD = "basic.auth.password";
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-04 05:52 UTC, deshankoswatte commented on features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/EndpointConfig.properties
> +basic.auth.password=admin
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-04 05:52 UTC, deshankoswatte commented on features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/RecoveryEndpointConfig.properties
> +basic.auth.password=admin
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-04 05:52 UTC, deshankoswatte commented on features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/RecoveryEndpointConfig.properties.j2
> +basic.auth.password={{identity.auth_framework.endpoint.basic_auth_password}}
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-04 05:52 UTC, deshankoswatte commented on features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/EndpointConfig.properties.j2
> +basic.auth.password={{identity.auth_framework.endpoint.basic_auth_password}}
Fixed with https://github.com/wso2/carbon-identity-framework/pull/3968/commits/87f4579c071f7d64026c1f53842e350b6f532c4e.

2022-08-08 05:51 UTC, rksk approved these changes

2022-08-08 05:51 UTC, merged