Introduce a config to update console & myaccount callback url
wso2/carbon-identity-framework pull request #5304
Opened 2023-12-13 03:34 UTC by UdeshAthukorala

### Proposed changes in this pull request

- Introduce a toml config to update console & myaccount callback url

### Related Issue

- https://github.com/wso2/product-is/issues/18164

2023-12-15 04:14 UTC, madurangasiriwardena commented on components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java
>                  ApplicationConstants.MY_ACCOUNT_APPLICATION_NAME.equals(name);
```suggestion
        return isConsole(name) || isMyAccount(name);
```

2023-12-15 08:57 UTC, UdeshAthukorala commented on components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java
>                  ApplicationConstants.MY_ACCOUNT_APPLICATION_NAME.equals(name);
Addressed with https://github.com/wso2/carbon-identity-framework/pull/5304/commits/a88bf6adea4698816742f7400abe77a68795a33b

2023-12-21 04:37 UTC, Thisara-Welmilla approved these changes

2023-12-21 05:38 UTC, Thisara-Welmilla commented
Shall we check the `tenant_context.require_super_tenant_in_urls` config and based on that add `/t/carbon.super` in path.

2023-12-21 05:39 UTC, Thisara-Welmilla requested changes
Shall we check the `tenant_context.require_super_tenant_in_urls` config and based on that add `/t/carbon.super` in path.

2023-12-22 03:01 UTC, UdeshAthukorala commented
> Shall we check the `tenant_context.require_super_tenant_in_urls` config and based on that add `/t/carbon.super` in path.

Addressed with https://github.com/wso2/carbon-identity-framework/pull/5304/commits/7b8bd9e4e79c57caa971e38fd823482904e4c13c

2023-12-29 04:49 UTC, Thisara-Welmilla approved these changes

2023-12-29 12:42 UTC, merged