Add XACML DAO JDBC implementation
wso2/carbon-identity-framework pull request #5792
Opened 2024-07-12 11:14 UTC by Yoshani

### Proposed changes in this pull request

Introduces the JDBC implementation for XACML.

### When should this PR be merged

Upon review

### Related PRs
- PR https://github.com/wso2/carbon-identity-framework/pull/5686

### Related issues
- Issue https://github.com/wso2/product-is/issues/20000

### Checklist (for reviewing)

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description.
- [ ] **Is the PR labeled correctly?**

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled.

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests.
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/).

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components.
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?**
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes should be documented.
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented.
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

2024-07-16 10:56 UTC, darshanasbg requested changes

2024-07-17 04:59 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/DAOConstants.java
> +        public static final String LAST_MODIFIED_USER = "LAST_MODIFIED_USER";
It stores the username

2024-07-17 05:39 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/DAOConstants.java
> +        public static final String USER = "USERNAME";
Also stores the username

2024-07-17 05:44 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/DAOConstants.java
> +        public static final String STATUS_COUNT = "COUNT";
Count is not a column in the table, it's just a constant used when retrieving a status count from db, thus moved it out from EntitlementTableColumns class

2024-07-17 09:14 UTC, darshanasbg commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/DAOConstants.java
> +        public static final String LAST_MODIFIED_USER = "LAST_MODIFIED_USER";
Cant we store userid?

2024-07-22 05:29 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/JDBCConfigDAOImpl.java
> +        Connection connection = IdentityDatabaseUtil.getDBConnection(false);
Refactored

2024-07-22 05:43 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/DAOConstants.java
> +        public static final String LAST_MODIFIED_USER = "LAST_MODIFIED_USER";
It will be a behavioral change from registry impl since `lastModifiedUser` is a property of the PolicyDTO object.

2024-07-23 11:31 UTC, darshanasbg requested changes

2024-07-25 05:34 UTC, Yoshani commented on components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/dao/JDBCConfigDAOImpl.java
> +            EntitlementEngine.getInstance().invalidatePolicyCache();
Moved the caching logic out

2024-08-01 04:35 UTC, Yoshani commented
Closing since this will be covered with https://github.com/wso2/carbon-identity-framework/pull/5826.

2024-08-01 04:35 UTC, closed without merging